export const TYPES = {
	Application: Symbol.for("Application"),
	Logger: Symbol.for("Logger"),
	Database: Symbol.for("Database"),
	Repository: Symbol.for("Repository"),
	TokenService: Symbol.for("TokenService"),
	UserRepository: Symbol.for("UserRepositroy"),
	UserService: Symbol.for("UserService"),
	UserController: Symbol.for("UserController"),
	TrackService: Symbol.for("TrackService"),
	TrackController: Symbol.for("TrackController"),
	FileService: Symbol.for("FileSerivce"),
	PlaylistController: Symbol.for("PlaylistController"),
	PlaylistService: Symbol.for("PlaylistService"),
	PlaylistRepository: Symbol.for("PlaylistRepository"),
	FavoritesController: Symbol.for("FavoritesController"),
	FavoritesService: Symbol.for("FavoritesService"),
	ErrorMiddleWare: Symbol.for("ErrorMiddleware"),
};
